### ISSUE TITLE
Missing Stimuli

### ISSUE THREAD

**Issue by natsn** [natsn/sweetcrave#1]
Could you please upload a zip file of all the images?

**Comment by leadafm** [comment]
![binge54](https://cloud.githubusercontent.com/assets/15018643/10353101/b51f8940-6d08-11e5-880f-44753e7ac41a.jpg)
![binge91](https://cloud.githubusercontent.com/assets/15018643/10353104/b52086f6-6d08-11e5-8202-dded7801b3f0.jpg)
![binge123](https://cloud.githubusercontent.com/assets/15018643/10353105/b520cd64-6d08-11e5-93c6-217773611758.jpg)
![binge140](https://cloud.githubusercontent.com/assets/15018643/10353103/b52060cc-6d08-11e5-9fe2-74293a35e9f2.jpg)
![binge176](https://cloud.githubusercontent.com/assets/15018643/10353106/b52181dc-6d08-11e5-8e79-803bb02d5344.jpg)
![binge182](https://cloud.githubusercontent.com/assets/15018643/10353102/b51fac86-6d08-11e5-965e-3e46d8fb3554.jpg)
![binge1](https://cloud.githubusercontent.com/assets/15018643/10353107/b531400e-6d08-11e5-9d20-4d41fce7eb1b.jpg)
![binge16](https://cloud.githubusercontent.com/assets/15018643/10353108/b53200a2-6d08-11e5-8a13-a532075b21c2.jpg)
![binge17](https://cloud.githubusercontent.com/assets/15018643/10353109/b532b25e-6d08-11e5-952e-93eb433f2b92.JPG)
![binge19](https://cloud.githubusercontent.com/assets/15018643/10353110/b533fcc2-6d08-11e5-93b6-66dde6533139.JPG)
![binge20](https://cloud.githubusercontent.com/assets/15018643/10353112/b5353e02-6d08-11e5-9303-caf244afea85.jpg)
![binge22](https://cloud.githubusercontent.com/assets/15018643/10353111/b5346874-6d08-11e5-9619-8285fcd23b96.jpg)
![binge23](https://cloud.githubusercontent.com/assets/15018643/10353115/b5439e16-6d08-11e5-8bf0-9bb5d5c7422c.jpg)
![binge26](https://cloud.githubusercontent.com/assets/15018643/10353113/b542b046-6d08-11e5-9449-b9ece488d7ef.jpg)
![binge28](https://cloud.githubusercontent.com/assets/15018643/10353114/b5438886-6d08-11e5-90af-3b16b07f9798.jpg)
![binge29](https://cloud.githubusercontent.com/assets/15018643/10353117/b5480ca8-6d08-11e5-8a12-3b242461b05d.jpg)
![binge43](https://cloud.githubusercontent.com/assets/15018643/10353116/b5459b94-6d08-11e5-86f0-726bfd969bf8.jpg)
![binge45](https://cloud.githubusercontent.com/assets/15018643/10353118/b548fd0c-6d08-11e5-9147-15cb58f7f3e4.jpg)
![binge51](https://cloud.githubusercontent.com/assets/15018643/10353119/b5540972-6d08-11e5-8a47-0106b56a2b89.jpg)
![binge53](https://cloud.githubusercontent.com/assets/15018643/10353120/b555c8a2-6d08-11e5-8149-f4e1fb06761c.jpg)

**Comment by leadafm** [comment]
![water6](https://cloud.githubusercontent.com/assets/15018643/10353152/f7e5e9a4-6d08-11e5-9921-ff8cab2bb013.jpg)
![water7](https://cloud.githubusercontent.com/assets/15018643/10353153/f7e67784-6d08-11e5-8218-6bc88e938136.jpg)
![water8](https://cloud.githubusercontent.com/assets/15018643/10353155/f7e720b2-6d08-11e5-91f7-753dd859f0e9.jpg)
![water9](https://cloud.githubusercontent.com/assets/15018643/10353154/f7e6b1c2-6d08-11e5-8e78-27d7e1e5ce0c.jpg)
![water10](https://cloud.githubusercontent.com/assets/15018643/10353156/f7e7e380-6d08-11e5-9f8f-0466c5facfc3.jpg)
![water11](https://cloud.githubusercontent.com/assets/15018643/10353157/f7e7e68c-6d08-11e5-8e0d-167aaaa7d14b.jpg)
![water12](https://cloud.githubusercontent.com/assets/15018643/10353160/f7f7d0ec-6d08-11e5-981e-77a8ea291a0d.jpg)
![water13](https://cloud.githubusercontent.com/assets/15018643/10353159/f7f76382-6d08-11e5-842b-f38a1ee6e6c3.jpg)
![water14](https://cloud.githubusercontent.com/assets/15018643/10353158/f7f75194-6d08-11e5-872a-6cd4cd286442.jpg)
![water15](https://cloud.githubusercontent.com/assets/15018643/10353162/f7f9618c-6d08-11e5-8908-66f6bba39fde.jpg)
![water16](https://cloud.githubusercontent.com/assets/15018643/10353161/f7f955de-6d08-11e5-9eee-d85df4fca280.jpg)
![water17](https://cloud.githubusercontent.com/assets/15018643/10353163/f7f9dd38-6d08-11e5-9198-986f5b1b69f4.jpg)
![water18](https://cloud.githubusercontent.com/assets/15018643/10353165/f808f57a-6d08-11e5-90dd-aefa8ed61df3.jpg)
![water19](https://cloud.githubusercontent.com/assets/15018643/10353164/f8090600-6d08-11e5-8b6b-8da4ae0b9554.jpg)
![water20](https://cloud.githubusercontent.com/assets/15018643/10353167/f80c0e7c-6d08-11e5-82b9-16fe17aaf7cf.jpg)
![water1](https://cloud.githubusercontent.com/assets/15018643/10353168/f80c9716-6d08-11e5-81fd-8accbeba2538.jpg)
![water2](https://cloud.githubusercontent.com/assets/15018643/10353169/f80cc5a6-6d08-11e5-9183-a95d5d44573f.jpg)
![water3](https://cloud.githubusercontent.com/assets/15018643/10353166/f80afc08-6d08-11e5-94f5-349685dce295.jpg)
![water4](https://cloud.githubusercontent.com/assets/15018643/10353171/f81b2dd0-6d08-11e5-901d-4b4a220fb4bd.jpg)
![water5](https://cloud.githubusercontent.com/assets/15018643/10353170/f81a8844-6d08-11e5-8c67-98a3ff709e4a.jpg)

**Comment by natsn** [comment]
THANKS! I will add these to the code :dancer:
